In [22]:
#QUESTION A1
import pandas as pd
import numpy as np

#to find dimensionality of vector space:
def dimensionality(matrix):
    return matrix.shape[1]

#to find number of vectors in the vector space
def vector_number(matrix):
    return matrix.shape[0]

#to find ranf of matrix A
def find_rank(matrix):
    return np.linalg.matrix_rank(matrix)

#to find cost of each product available for sale using Pseudo-Inverse
def find_cost(A,C):
    A_pseudo_inv = np.linalg.pinv(A)
    cost = A_pseudo_inv @ C
    return cost
    
file_path = 'C:\\Users\\Bhavi\\Downloads\\Lab Session Data.xlsx'
sheet_name = 'Purchase data'

data = pd.read_excel(file_path, sheet_name=sheet_name)

A = data[['Candies (#)', 'Mangoes (Kg)', 'Milk Packets (#)']].values  
C = data[['Payment (Rs)']].values     

print("Matrix A:")
print(A)
print("\nMatrix C:")
print(C)
print('\nthe dimensionality of the vector space:',dimensionality(A))
print('\nthe number of vectors in the vector space:',vector_number(A))
print('\nthe rank of matrix A:',find_rank(A))
print('\nthe cost of each product:',find_cost(A,C))

Matrix A:
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]

Matrix C:
[[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]]

the dimensionality of the vector space: 3

the number of vectors in the vector space: 10

the rank of matrix A: 3

the cost of each product: [[ 1.]
 [55.]
 [18.]]


In [24]:
#QUESTION A2

import pandas as pd
import numpy as np

#Use the Pseudo-inverse to calculate the model vector X for predicting the cost of the products 
#available with the vendor
def calculate_model_vector(A, C):
    A_pseudo_inv = np.linalg.pinv(A)
    X = A_pseudo_inv @ C
    return X
   
file_path = 'C:\\Users\\Bhavi\\Downloads\\Lab Session Data.xlsx'
sheet_name = 'Purchase data'

data = pd.read_excel(file_path, sheet_name=sheet_name)

A = data[['Candies (#)', 'Mangoes (Kg)', 'Milk Packets (#)']].values  
C = data[['Payment (Rs)']].values     
print('\nmodel vector for predicting the cost of the products available with the vendor',calculate_model_vector(A, C))


model vector for predicting the cost of the products available with the vendor [[ 1.]
 [55.]
 [18.]]


In [26]:
#QUESTION A3

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

# Function to classify customers based on payment
def classify_customers(data, payment_column, threshold=200):
    data['Class'] = np.where(data[payment_column] > threshold, 'RICH', 'POOR')
    return data

# Function to train and evaluate a classifier model
def train_evaluate_classifier(data, feature_columns, class_column):
    X = data[feature_columns]
    y = data[class_column]
    
    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=37)
    
    # Initialize and train the logistic regression model
    model = LogisticRegression(max_iter=1000)
    model.fit(X_train, y_train)
    
    # Predict on the test set
    y_pred = model.predict(X_test)
    
    # Calculate accuracy and classification report
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    
    return accuracy, report

if __name__ == "__main__":
    # File path and sheet name
    file_path = 'C:\\Users\\Bhavi\\Downloads\\Lab Session Data.xlsx'
    sheet_name = 'Purchase data'
    
    # Load the data
    purchase_df = pd.read_excel(file_path, sheet_name=sheet_name)
    
    # Define feature columns and class column
    feature_columns = ['Candies (#)', 'Mangoes (Kg)', 'Milk Packets (#)']
    class_column = 'Class'
    
    # Classify customers as RICH or POOR
    purchase_df = classify_customers(purchase_df, 'Payment (Rs)')
    
    # Train and evaluate the classifier model
    accuracy, report = train_evaluate_classifier(purchase_df, feature_columns, class_column)
    
    # Print results
    print(f"Accuracy: {accuracy}")
    print("Classification Report:")
    print(report)

Accuracy: 0.8
Classification Report:
              precision    recall  f1-score   support

        POOR       0.50      1.00      0.67         1
        RICH       1.00      0.75      0.86         4

    accuracy                           0.80         5
   macro avg       0.75      0.88      0.76         5
weighted avg       0.90      0.80      0.82         5



In [62]:
#QUESTION A4

import pandas as pd
import statistics

#to calculate mean
def calc_mean(price):
    return statistics.mean(price)

#to calculate variance
def calc_variance(price):
    return statistics.variance(price)

#to find the sample mean for price data on wednesdays
def calc_sample_mean(prices):
    return statistics.mean(prices)

#to find the probability of making a loss over stock
def calc_loss(chg):
    loss_count = chg[chg < 0].count()
    total_count = chg.count()
    return loss_count / total_count if total_count > 0 else 0

#to find the probability of making a profit over stock
def calc_profit(chg):
    profit_count = chg[chg > 0].count()
    total_count = chg.count()
    return profit_count / total_count if total_count > 0 else 0

def calc_conditional_profit_prob(chg_wed, chg):
    prob_profit_given_wed = calc_profit(chg_wed)
    prob_profit = calc_profit(chg)
    prob_wed = len(chg_wed) / len(chg) if len(chg) > 0 else 0
    return prob_profit_given_wed / prob_wed if prob_wed > 0 else 0

file_path = 'C:\\Users\\Bhavi\\Downloads\\Lab Session Data.xlsx'
sheet_name = 'IRCTC Stock Price'

stock_data = pd.read_excel(file_path, sheet_name=sheet_name)

price = stock_data['Price'].dropna()

wednesday_prices = stock_data[stock_data['Day'] == 'Wed']['Price'].dropna()

april_prices = stock_data[stock_data['Month'] == 'Apr']['Price'].dropna()

chg = stock_data['Chg%'].dropna()

chg_wed = stock_data[stock_data['Day'] == 'Wed']['Chg%'].dropna()

print('mean of price:', calc_mean(price))
print('variance of price:', calc_variance(price))
print('sample mean for wednesday prices:', calc_sample_mean(wednesday_prices))

if calc_sample_mean(wednesday_prices) > calc_mean(price):
    print('sample mean is higher than population mean for wednesday prices sample')
elif calc_sample_mean(wednesday_prices) == calc_mean(price):
    print('sample mean is equal to population mean for wednesday prices sample')
else:
    print('sample mean is lesser than population mean for wednesday prices sample')
    
print('sample mean for april prices:', calc_sample_mean(april_prices))
if calc_sample_mean(april_prices) > calc_mean(price):
    print('sample mean is higher than population mean for april prices sample')
elif calc_sample_mean(april_prices) == calc_mean(price):
    print('sample mean is equal to population mean for april prices sample')
else:
    print('sample mean is lesser than population mean for april prices sample')

print('probability of making a loss over stock:', calc_loss(chg))
print('probability of making a profit over stock on wednesday:', calc_profit(chg_wed))
print('conditional probability of making a profit, given that it is wednesday:', calc_conditional_profit_prob(chg_wed, chg))

mean of price: 1560.663453815261
variance of price: 58732.365352539186
sample mean for wednesday prices: 1550.706
sample mean is lesser than population mean for wednesday prices sample
sample mean for april prices: 1698.9526315789474
sample mean is higher than population mean for april prices sample
probability of making a loss over stock: 0.4979919678714859
probability of making a profit over stock on wednesday: 0.42
conditional probability of making a profit, given that it is wednesday: 2.0916
